from opensearchpy import OpenSearch

from src.config import settings


def _build_ingest_pipeline_body() -> dict:
    return {
        "description": "Generate embedding from scene_description + video_title",
        "processors": [
            {
                "script": {
                    "source": (
                        "ctx['combined_text'] = "
                        "((ctx['scene_description'] ?: '') + ' ' + (ctx['video_title'] ?: '')).trim()"
                    )
                }
            },
            {
                "text_embedding": {
                    "model_id": settings.model_id,
                    "field_map": {
                        "combined_text": "embedding"
                    },
                }
            },
            {
                "remove": {
                    "field": "combined_text"
                }
            },
        ],
    }


def _build_index_body() -> dict:
    return {
        "settings": {
            "index.knn": True,
            "number_of_shards": 1,
            "number_of_replicas": 0,
            "default_pipeline": settings.ingest_pipeline_name,
        },
        "mappings": {
            "properties": {
                # Video-level fields
                "video_id": {"type": "keyword"},
                "video_title": {
                    "type": "text",
                    "fields": {"keyword": {"type": "keyword"}},
                },
                "video_description": {"type": "text"},
                "video_tags": {"type": "keyword"},
                "video_duration_sec": {"type": "float"},
                "video_created_at": {"type": "date"},
                # Scene-level fields
                "scene_id": {"type": "keyword"},
                "scene_description": {"type": "text"},
                "start_time_sec": {"type": "float"},
                "end_time_sec": {"type": "float"},
                # Embedding (auto-generated by ingest pipeline)
                "embedding": {
                    "type": "knn_vector",
                    "dimension": settings.embedding_dimension,
                    "method": {
                        "name": "hnsw",
                        "engine": "lucene",
                        "parameters": {
                            "ef_construction": 128,
                            "m": 16,
                        },
                    },
                    "space_type": "cosinesimil",
                },
            }
        },
    }


SEARCH_PIPELINE_BODY = {
    "description": "Score normalization for hybrid search",
    "phase_results_processors": [
        {
            "normalization-processor": {
                "normalization": {"technique": "min_max"},
                "combination": {
                    "technique": "arithmetic_mean",
                    "parameters": {"weights": [0.3, 0.7]},
                },
            }
        }
    ],
}


def ensure_ingest_pipeline(client: OpenSearch) -> None:
    client.ingest.put_pipeline(
        id=settings.ingest_pipeline_name,
        body=_build_ingest_pipeline_body(),
    )


def ensure_index(client: OpenSearch) -> None:
    if not client.indices.exists(index=settings.index_name):
        client.indices.create(
            index=settings.index_name,
            body=_build_index_body(),
        )


def ensure_search_pipeline(client: OpenSearch) -> None:
    client.http.put(
        url=f"/_search/pipeline/{settings.search_pipeline_name}",
        body=SEARCH_PIPELINE_BODY,
    )
